language: node_js

node_js:
  - 'node'

jobs:
  include:
    - stage: test
      addons:
        firefox: 'latest-esr'
      before_install:
        - npm install -g wiredeps@0.2
        - wiredeps --default-branch=master --branch=$TRAVIS_BRANCH --tag=$TRAVIS_TAG --verbose
      script:
        - TEST_BROWSERS=Firefox,ChromeHeadless xvfb-run npm run all
    - stage: update integration test
      script: './tasks/stages/update-integration-test'
    - stage: update examples
      script: './tasks/stages/update-examples'

stages:
  - test
  - name: update integration test
    if: tag =~ ^v\d
  - name: update examples
    if: tag =~ ^v\d